apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:    
            claimName: ebs-claim
      containers:
      - name: web
        image: yanar/web:120
        volumeMounts:
          - name: vol
            mountPath: /var/www/html/public/storage
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 5
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:    
            claimName: ebs-claim
      containers:
      - name: php
        image: yanar/php:120
        volumeMounts:
          - name: vol
            mountPath: /var/www/html/public/storage
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  externalName: k8s.c1luoeubmchn.me-south-1.rds.amazonaws.com 
  selector:
    app: mysql
  type: ExternalName
status:
  loadBalancer: {}
