apiVersion: v1
kind: Service
metadata:
  name: nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:me-south-1:302203017279:certificate/03daaa7a-3984-4c15-bb1f-3a6ff04e9e5f"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: web
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  externalName: k8s.c1luoeubmchn.me-south-1.rds.amazonaws.com 
  selector:
    app: mysql
  type: ExternalName
status:
  loadBalancer: {}
