apiVersion: v1
kind: StorageClass
metadata:
  name: datastore
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOption:
  - debug
volumeBindingMode: Immediate
